language: "node_js"
node_js:
  - 14.0
  - 12.0
  - 10.0
  - 8.0
install:
  - npm install
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
